name: qremo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.17
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/Maths.svg  # Corrected the path here from `asset/Maths.svg` to `assets/Maths.svg`
    - asset/Biology.svg
    - asset/Physics.svg
    - asset/Chemistry.svg
    - asset/Geography.svg
    - asset/History.svg
    - asset/English.svg
    